routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Home Page */

Route::get('/', 'HomeController@index')->name('welcome');
Route::get('about', 'HomeController@about')->name('about');
Route::get('contact', 'HomeController@contact')->name('contact');
Route::get('infoproduct/{id}', 'ProductController@show')->name('infoproduct');
Route::get('kategori/{id}', 'HomeController@kategori')->name('kategori');
Route::get('buktiTransaksi/{id}', 'HomeController@invoice')->name('buktiTransaksi');
Route::get('PrintbuktiTransaksi/{id}', 'HomeController@print_invoice')->name('print-invoice');

/* Referal */
Route::get('/Shop/{user}', 'ReplikaController@index');
Route::get('/infoproduct/{id}/Shop/{user}', 'ReplikaController@detailProduk');
Route::post('keranjangbeli/Shop/{user}', 'ReplikaController@keranjangBeli');
Route::get('listkeranjangbelanja/Shop/{user}', 'ReplikaController@keranjangBelanja');
Route::post('prosesBeli/{user}', 'ReplikaController@prosescheckout');
Route::get('hapuscart/{key}/Shop/{user}', 'ReplikaController@hapusproduk');

/* Cart */
Route::post('keranjangbeli', 'HomeController@keranjangbeli')->name('keranjangbeli');
Route::get('listkeranjangbelanja', 'TransaksiController@listkeranjangbeli')->name('listkeranjangbelanja');
Route::get('hapuscart/{key}', 'TransaksiController@hapuscart')->name('hapus.cart');
Route::post('prosesBeli', 'TransaksiController@prosesbeli')->name('proses.orderbeli');

/* End Cart */

/* Raja Ongkir */
Route::get('/province', 'RajaongkirController@get_province')->name('province');
Route::get('/kota/{id}', 'RajaongkirController@get_city')->name('city');
Route::get('/origin={city_origin}&destination={city_destination}&courier={courier}', 'RajaongkirController@get_ongkir')->name('ongkir');
/* End Raja Ongkir */

/* Link Whatsapp */
Route::post('whatsapp', 'LinkController@index')->name('whatsapp');
/* End Home Page */

/* Login Page & Authentikasi */
Route::get('administrator', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@login')->name('postlogin');
Route::get('logout', 'LoginController@logout')->name('logout');
/* End Login Page & Authentikasi */

Route::get('dashboard', 'HomeController@admin')->name('dashboard');

/* Administrator */
Route::group(['middleware' => 'auth', 'CekRole:admin'], function () {
    /* Profile */
    Route::get('profile', 'ProfileController@index')->name('admin.profile');
    Route::get('profile/edit/{id}', 'ProfileController@edit')->name('profile.edit');
    Route::post('profile/update/{id}', 'ProfileController@update')->name('profile.update');

    /* Product */
    Route::get('product', 'ProductController@index')->name('admin.produk');
    Route::get('product/add', 'ProductController@create')->name('produk.add');
    Route::get('product/edit/{id}', 'ProductController@edit')->name('produk.edit');
    Route::post('product', 'ProductController@store')->name('produk.store');
    Route::post('product/update/{id}', 'ProductController@update')->name('produk.update');
    Route::get('product/{id}', 'ProductController@destroy')->name('produk.delete');

    /* Mahasiswa */
    Route::get('mahasiswa', 'MahasiswaController@index')->name('admin.mahasiswa');
    Route::get('mahasiswa/add', 'MahasiswaController@create')->name('mahasiswa.add');
    Route::get('mahasiswa/edit/{id}', 'MahasiswaController@edit')->name('mahasiswa.edit');
    Route::post('mahasiswa', 'MahasiswaController@store')->name('mahasiswa.store');
    Route::post('mahasiswa/update/{id}', 'MahasiswaController@update')->name('mahasiswa.update');
    Route::get('mahasiswa/{id}', 'MahasiswaController@destroy')->name('mahasiswa.delete');

    /* Transaksi */
    Route::get('transaksibeli', 'TransaksibeliController@index')->name('admin.transaksibeli');
    Route::get('transaksibeli/show/{id}', 'TransaksibeliController@show')->name('transaksibeli.show');
    Route::get('konfirmasibayar/{id}', 'TransaksibeliController@konfirmasiBeli')->name('konfirmasi.bayar');
    Route::get('batalBeli/{id}', 'TransaksibeliController@batalBeli')->name('batal.beli');

    /* Withdraw */
    Route::get('transaksiwithdraw', 'TransaksiwithdrawController@index')->name('admin.withdraw');
    Route::get('detailwithdraw/{id}', 'TransaksiwithdrawController@show')->name('detailwithdraw.show');
    Route::get('konfirmasiwithdraw/{id}', 'TransaksiwithdrawController@konfirmasiWithdraw')->name('konfirmasi.withdraw');

    /* Link Referal */
    // Route::get('linkreferal', 'KodereferalController@index')->name('admin.linkreferal');
    // Route::get('linkreferal/add', 'KodereferalController@create')->name('linkreferal.add');
    // Route::get('linkreferal/edit/{id}', 'KodereferalController@edit')->name('linkreferal.edit');
    // Route::post('linkreferal', 'KodereferalController@store')->name('linkreferal.store');
    // Route::post('linkreferal/update/{id}', 'KodereferalController@update')->name('linkreferal.update');
    // Route::get('linkreferal/{id}', 'KodereferalController@destroy')->name('linkreferal.delete');

    /* Kategori */
    // Route::get('kategori', 'KategoriController@index')->name('admin.kategori');
    // Route::get('kategori/edit/{id}', 'KategoriController@edit')->name('kategori.edit');
    // Route::post('kategori', 'KategoriController@store')->name('kategori.store');
    // Route::post('kategori/update/{id}', 'KategoriController@update')->name('kategori.update');
    // Route::get('kategori/delete/{id}', 'KategoriController@destroy')->name('kategori.delete');

});
/* End Administrator */

/* Mahasiswa */
    Route::group(['middleware' => ['auth', 'CekRole:mahasiswa'], 'prefix' => 'Student'], function () {
        Route::namespace('Student')->group(function () {
            Route::resource('profilemhs', 'ProfilemhsController');
            Route::resource('transaksimhs', 'TransaksimhsController');
            Route::resource('withdraw', 'WithdrawController');
        });
    });
/* End Mahasiswa */

app/Http/Controllers/TransaksiwithdrawController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Withdraw;

class TransaksiwithdrawController extends Controller
{
    public function index(){
        $value = Withdraw::paginate(5);

        return view('admin.transaksiwithdraw.index', compact('value'));
    }

    public function show($id){
        $value = Withdraw::find($id);

        return view('admin.transaksiwithdraw.show', compact('value'));
    }

    public function konfirmasiwithdraw($id){
        $data = Withdraw::find($id);

        $data->update([
            'status' => 'Success',
        ]);

        return redirect()->route('admin.withdraw');
    }
}

resources/views/admin/transaksiwithdraw/index.blade.php
@extends('layout.admin_layouts')

@section('title', 'Administrator | Data Transaksi')

@section('content')
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
        navbar-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark"
                            href="{{ route('dashboard') }}">Administrator</a></li>
                    <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Data Transaksi</li>
                </ol>
                <h6 class="font-weight-bolder mb-0">Data Transaksi</h6>
                <li class="nav-item d-xl-none mt-3 d-flex align-items-center">
                    <a href="#" class="nav-link text-body p-0" id="iconNavbarSidenav">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </a>
                </li>
            </nav>
            <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                <div class="ms-md-auto pe-md-3 mt-3 d-flex align-items-center">
                    <div class="input-group">
                        {{-- @php
                            dd(URL::current());
                        @endphp --}}
                        <form class="d-flex" action="{{ URL::current() }}" method="GET">
                            <input class="form-control me-2" placeholder="Cari ..." aria-label="Search" type="text"
                                name="cari" value="{{ request('cari') }}">
                            <button class="input-group-text" type="submit"><i class="fas fa-search"
                                    aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item mt-3 d-flex align-items-center">
                        <i class="fa fa-user"></i>
                        <span class="d-sm-inline text-sm">&nbsp;{{ Auth::user()->name }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->

    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0 p-3">
                        <div class="row">
                            <div class="col-6 d-flex align-items-center">
                                <h6 class="mb-0">Data Transaksi</h6>
                            </div>
                            {{-- <div class="col-6 text-end">
                                <a class="btn bg-gradient-success text-dark mb-0" style="font-size: 12px"
                                    href="{{ route('mahasiswa.add') }}"><i
                                        class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</a>
                            </div> --}}
                        </div>
                    </div>
                    <div class="card-body pb-0 p-3">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                    <tr>
                                        <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            No
                                        </th>
                                        <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            Tanggal Withdraw
                                        </th>
                                        <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            Kode Withdraw
                                        </th>
                                        {{-- <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            Nama Customer
                                        </th> --}}
                                        <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            Jumlah Withdraw
                                        </th>
                                        <th
                                            class="text-uppercase text-secondary text-dark text-xxs font-weight-bolder opacity-7 ps-2">
                                            Status
                                        </th>
                                        <th class="text-secondary opacity-7"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        // dd($transaksi->produk);
                                        $no = 1;
                                    @endphp
                                    @forelse ($value as $item)
                                        <tr>
                                            <td>
                                                <p class="text-xs font-weight-bold mb-0">{{ $no++ }}</p>
                                            </td>
                                            <td>
                                                <p class="text-xs font-weight-bold mb-0">
                                                    {{ Carbon\Carbon::parse($item->creted_at)->isoFormat('D MMMM Y') }}
                                                </p>
                                            </td>
                                            {{-- <td>
                                                @foreach ($item->detailtransaksi as $data)
                                                    <p class="text-xs font-weight-bold mb-0"> {{ $data->namacust }}</p>
                                                @endforeach
                                            </td> --}}
                                            <td>
                                                <p class="text-xs font-weight-bold mb-0">{{ $item->kode_withdraw }}</p>
                                            </td>
                                            <td>
                                                <p class="text-xs font-weight-bold mb-0">Rp.
                                                    {{ number_format($item->jumlah) }}</p>
                                            </td>
                                            <td>
                                                @if ($item->status == 'Proses')
                                                    <p class="text-xs font-weight-bold mb-0" style="color: orange">
                                                        {{ $item->status }}
                                                    </p>
                                                @endif
                                                @if ($item->status == 'Success')
                                                    <p class="text-xs font-weight-bold mb-0" style="color: rgb(6, 226, 6)">
                                                        {{ $item->status }}
                                                    </p>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('detailwithdraw.show', $item->id) }}"
                                                    class="badge badge-sm bg-gradient-primary" data-toggle="tooltip"
                                                    data-original-title="Detail">
                                                    <i class="fa fa-file-invoice-dollar"></i>&nbsp;Detail
                                                </a>
                                                {{-- <a href="#" class="badge badge-sm bg-gradient-danger delete"
                                                    data-id="{{ $item->id }}" data-nama="{{ $item->nama }}"
                                                    data-toggle="tooltip" data-original-title="Delete">
                                                    <i class="fa fa-trash me-sm-1"></i>
                                                </a> --}}
                                            </td>
                                        @empty
                                            <td class="text-sm" colspan="15" align="center">
                                                <i>Data tidak tersedia</i>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                            {{ $value->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
{{-- @section('script')
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js"
        integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
    <script>
        $('.delete').click(function() {
            var mhsid = $(this).attr('data-id');
            var mhsname = $(this).attr('data-nama');
            swal({
                    title: "Apakah anda yakin?",
                    text: "Anda akan menghapus " + mhsname + "",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "mahasiswa/" + mhsid + ""
                        swal("Data Mahasiswa " + mhsname + " berhasil dihapus", {
                            icon: "success",
                        });
                    } else {
                        swal("Data Mahasiswa " + mhsname + " batal dihapus");
                    }
                });
        });
    </script>
@endsection --}}

resources/views/admin/transaksiwithdraw/show.blade.php
@extends('layout.admin_layouts')

@section('title', 'Administrator | Withdraw')

@section('content')
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur"
        navbar-scroll="true">
        <div class="container-fluid py-1 px-3">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark"
                            href="{{ route('dashboard') }}">Administrator</a></li>
                    <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark"
                            href="{{ route('withdraw.index') }}">Data Withdraw</a></li>
                </ol>
                <h6 class="font-weight-bolder mb-0">Detail Data Withdraw</h6>
            </nav>
            <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
                <div class="ms-md-auto pe-md-3 d-flex align-items-center">
                </div>
                <ul class="navbar-nav  justify-content-end">
                    <li class="nav-item d-flex align-items-center">
                        <i class="fa fa-user"></i>
                        <span class="d-sm-inline text-sm">&nbsp;{{ Auth::user()->name }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End Navbar -->

    <!-- Forms -->
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0 p-3">
                        <div class="row">
                            <div class="col-6 d-flex align-items-center">
                            </div>
                        </div>
                    </div>
                    <div class="card-body pb-0 p-3">
                        <div class="container">
                            <div class="col-md-6">
                                <label for="harga" class="form-label">Kode Withdraw</label>
                                <input type="text" class="form-control" id="kode_withdraw" name="kode_withdraw"
                                    placeholder="Kode Withdraw" value="{{ $value->kode_withdraw }}" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="nama" class="form-label">Nama Bank</label>
                                <input type="text" class="form-control" value="{{ $value->bank_name }}" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="nama" class="form-label">Nomor Rekening</label>
                                <input type="number" class="form-control" id="no_rek" name="no_rek"
                                    placeholder="Nomor Rekening" value="{{ $value->no_rek }}" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="nama" class="form-label">Atas Nama</label>
                                <input type="text" class="form-control" id="nama_rek" name="nama_rek"
                                    placeholder="Atas Nama" value="{{ $value->nama_rek }}" disabled>
                            </div>
                            <div class="col-md-6">
                                <label for="nama" class="form-label">Jumlah Withdraw</label>
                                <input type="number" class="form-control" id="jumlah" name="jumlah"
                                    placeholder="Jumlah Withdraw" value="{{ $value->jumlah }}" disabled>
                            </div>
                            <div class="col-12 mt-5">
                                <a href="{{ route('admin.withdraw') }}" type="button"
                                    class="btn btn-secondary float-start"><i class="fas fa-arrow-left"></i>&nbsp;Kembali</a>
                                <a href="{{ route('konfirmasi.withdraw', $value->id) }}"
                                    class="btn btn-success float-end"><i class="fas fa-check"></i>&nbsp;Konfirmasi</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection